import worker, { isAuthenticated, emailToTask } from './src/index.js';
import { createHash } from 'node:crypto';
const TOKEN = 'tt_' + 'a'.repeat(32);
const HASH = createHash('sha256').update(TOKEN).digest('hex');
const UID = '11111111-1111-1111-1111-111111111111';
const db = { tasks: [], tags: [], task_tags: [], projects: [], folders: [], api_tokens: [{ id: 't1', user_id: UID, token_hash: HASH }], email_senders: [{ id: 'e1', user_id: UID, email: 'robert@douglasmining.com' }], project_tags: [] };
let n = 0; const id = () => `00000000-0000-0000-0000-${String(++n).padStart(12, '0')}`;
// Tiny PostgREST imitation: eq/is/in filters, POST/PATCH/DELETE.
globalThis.fetch = async (url, init = {}) => {
  const u = new URL(url); const table = u.pathname.split('/').pop();
  const filters = [...u.searchParams].filter(([k]) => !['select','order','limit','or'].includes(k));
  const ors = [...u.searchParams].filter(([k]) => k === 'or').map(([, v]) => v.slice(1, -1).match(/[a-z_]+\.(?:ilike\.\*[^*]*\*|in\.\([^)]*\)|not\.is\.null|is\.null)/g) || []);
  const orMatch = (r) => ors.every((conds) => conds.some((c) => {
    const [k, op, ...rest] = c.split('.'); const v = rest.join('.');
    if (op === 'ilike') return (r[k] || '').toLowerCase().includes(decodeURIComponent(v).replace(/\*/g, '').toLowerCase());
    if (op === 'in') return v.slice(1, -1).split(',').map((x) => x.replace(/"/g, '')).includes(String(r[k]));
    if (op === 'not') return r[k] != null;
    if (op === 'is') return r[k] == null;
    return false;
  }));
  const match = (r) => filters.every(([k, v]) => {
    const [op, ...rest] = v.split('.'); const val = rest.join('.');
    if (op === 'eq') return String(r[k]) === val;
    if (op === 'is') return val === 'null' ? r[k] == null : String(r[k]) === val;
    if (op === 'in') return val.slice(1, -1).split(',').map(s => s.replace(/"/g,'')).includes(String(r[k]));
    if (op === 'not') return r[k] != null;
    if (op === 'lt') return r[k] && r[k] < val;
    if (op === 'gte') return r[k] && r[k] >= val;
    if (op === 'lte') return r[k] != null && (typeof r[k] === 'number' ? r[k] <= Number(val) : r[k] <= val);
    return true;
  });
  const m = init.method || 'GET'; const rows = db[table];
  const body = init.body ? JSON.parse(init.body) : null;
  const res = (d, s = 200) => new Response(d === null ? null : JSON.stringify(d), { status: s });
  if (m === 'GET') return res(rows.filter((r) => match(r) && orMatch(r)));
  if (m === 'POST') { const add = (Array.isArray(body) ? body : [body]).map(b => ({ id: id(), in_inbox: true, flagged: false, notes: '', created_at: new Date().toISOString(), parent_id: null, project_id: null, completed_at: null, dropped_at: null, due_at: null, defer_at: null, status: 'active', ...b })); rows.push(...add); return init.headers.Prefer ? res(add, 201) : res(null, 201); }
  if (m === 'PATCH') { rows.filter(match).forEach(r => Object.assign(r, body)); return res(null, 204); }
  if (m === 'DELETE') { db[table] = rows.filter(r => !match(r)); return res(null, 204); }
};
const env = { SUPABASE_URL: 'https://x.supabase.co', SUPABASE_SECRET_KEY: 'sb_secret_test', TIMEZONE: 'America/Chicago' };
const ctx = { waitUntil() {} };
const call = async (method, params, token = TOKEN) => {
  const r = await worker.fetch(new Request('https://mcp.todotooling.com/mcp', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }) }), env, ctx);
  return { status: r.status, body: r.status === 202 ? null : await r.json() };
};
const tool = async (name, args) => { const r = await call('tools/call', { name, arguments: args }); const c = r.body.result; if (c.isError) throw new Error(c.content[0].text); return JSON.parse(c.content[0].text); };
const assert = (c, m) => { if (!c) throw new Error('FAIL: ' + m); console.log('ok -', m); };

assert((await call('initialize', { protocolVersion: '2025-06-18' }, 'tt_wrongwrongwrongwrongwrong')).status === 401, 'bad token -> 401');
const init = await call('initialize', { protocolVersion: '2025-06-18' });
assert(init.body.result.protocolVersion === '2025-06-18' && init.body.result.capabilities.tools, 'initialize');
assert((await worker.fetch(new Request('https://mcp.todotooling.com/mcp', { method: 'POST', headers: { Authorization: `Bearer ${TOKEN}` }, body: JSON.stringify({ jsonrpc: '2.0', method: 'notifications/initialized' }) }), env, ctx)).status === 202, 'notification -> 202');
const list = await call('tools/list');
const TOOL_NAMES = list.body.result.tools.map((x) => x.name);
assert(list.body.result.tools.length === 16 && list.body.result.tools.every(t => t.inputSchema && !t.run), 'tools/list: 16 tools, no internals leaked');
const cap = await tool('capture', { title: 'Call GVEC about utilities' });
assert(cap.in_inbox && cap.title === 'Call GVEC about utilities', 'capture lands in inbox');
assert((await tool('list_inbox', {})).count === 1, 'list_inbox shows it');
await tool('create_project', { name: 'Click Plumbing', folder: 'PRIORITIES' });
const up = await tool('update_task', { id: cap.id, project: 'click plumbing', tags: ['Phone', 'Waiting : Hiro'], due: '2026-09-25', flagged: true });
assert(!up.in_inbox && up.project === 'Click Plumbing' && up.tags.includes('Waiting : Hiro') && up.due === '2026-09-25' && up.flagged, 'update_task clarifies out of inbox');
assert(db.task_tags.every(l => l.user_id === UID), 'task_tags scoped to user');
const byTag = await tool('list_tasks', { tag: 'Waiting' });
assert(byTag.count === 1, 'parent tag filter includes children');
const tags = await tool('list_tags', {});
assert(tags.find(t => t.label === 'Waiting : Hiro').open_tasks === 1, 'list_tags counts');
const projs = await tool('list_projects', {});
assert(projs[0].folder === 'PRIORITIES' && projs[0].open_actions === 1, 'list_projects with folder + counts');
const oneShot = await tool('capture', { title: 'Schedule backflow test', project: 'click plumbing', tags: ['Phone', 'Waiting : Hiro'], due: '2026-10-01', planned: '2026-09-28', flagged: true });
assert(oneShot.planned === '2026-09-28' && db.tasks.find((x) => x.id === oneShot.id).planned_at === '2026-09-28T14:00:00.000Z', 'capture: planned date at 9am local');
assert(!oneShot.in_inbox && oneShot.project === 'Click Plumbing' && oneShot.tags.length === 2 && oneShot.due === '2026-10-01' && oneShot.flagged, 'capture sets project, tags, due, flag in one call');
assert((await tool('list_tasks', { search: 'backflow hiro' })).count === 1, 'search: words across title + tag must all match');
assert((await tool('list_tasks', { search: 'plumbing' })).items.some((x) => x.title === 'Schedule backflow test'), 'search: matches project name');
assert((await tool('list_tasks', { search: 'backflow nope' })).count === 0, 'search: every word must match');
await tool('create_project', { name: 'Seq', kind: 'sequential', complete_with_last: true });
const s1 = await tool('capture', { title: 'Seq first', project: 'Seq' });
const s2 = await tool('capture', { title: 'Seq second', project: 'Seq' });
assert(db.tasks.find((x) => x.id === s2.id).sort > db.tasks.find((x) => x.id === s1.id).sort, 'capture into project appends at the end');
const nextActs = await tool('list_tasks', { project: 'Seq', available_only: true });
assert(nextActs.count === 1 && nextActs.items[0].id === s1.id, 'available_only: sequential shows only the head');
const seqRow = (await tool('list_projects', {})).find((x) => x.name === 'Seq');
assert(seqRow.kind === 'sequential' && seqRow.complete_with_last && seqRow.next_action.id === s1.id, 'list_projects: kind, auto-complete, next action');
const est = await tool('update_task', { id: s1.id, estimate_minutes: 10 });
assert(est.estimate_minutes === 10, 'update_task: estimate');
assert((await tool('list_tasks', { project: 'Seq', max_minutes: 15 })).items.every((x) => x.estimate_minutes <= 15), 'list_tasks: max_minutes');
const pTagged = await tool('update_project', { project: 'Seq', flagged: true, tags: ['Errands'] });
assert(pTagged.flagged && pTagged.tags.join() === 'Errands', 'update_project: flag + tags');
const viaTag = await tool('list_tasks', { tag: 'Errands' });
assert(viaTag.count === 2 && viaTag.items[0].project_tags.includes('Errands'), 'tag filter includes actions inherited from project tags');
const fl = await tool('list_flagged', {});
assert(fl.count >= 2 && fl.by_project.Seq && fl.by_project.Seq.length === 2, 'list_flagged includes actions of flagged projects');
const kindChange = await tool('update_project', { project: 'Seq', kind: 'parallel', complete_with_last: false });
assert(kindChange.kind === 'parallel' && kindChange.complete_with_last === false, 'update_project: kind + complete_with_last');
assert((await tool('list_tasks', { project: 'Seq', available_only: true })).count === 2, 'parallel: all available');
const moved = await tool('update_project', { project: 'Click Plumbing', folder: 'Businesses', status: 'on_hold' });
assert(moved.folder === 'Businesses' && moved.status === 'on_hold' && db.folders.length === 2, 'update_project moves to new folder + status');
const unfiled = await tool('update_project', { project: 'click plumbing', folder: null, name: 'Click Plumbing Co' });
assert(unfiled.folder === null && unfiled.name === 'Click Plumbing Co', 'update_project removes folder + renames');
const nf = await tool('create_folder', { name: 'Personal' });
const again = await tool('create_folder', { name: 'personal' });
assert(nf.id === again.id, 'create_folder is idempotent by name');
const ren = await tool('update_folder', { folder: 'Personal', name: 'Home' });
assert(ren.name === 'Home' && !ren.archived, 'update_folder renames');
const arch = await tool('update_folder', { folder: 'Home', archived: true });
assert(arch.archived, 'update_folder archives an empty folder');
const lf = await tool('list_folders', {});
assert(!lf.find((f) => f.name === 'Home') && (await tool('list_folders', { include_archived: true })).find((f) => f.name === 'Home').archived, 'list_folders hides archived unless asked');
assert(!TOOL_NAMES.some((n) => /delete/.test(n)), 'no delete tools exposed');
const sub = await tool('capture', { title: 'Get meter number' });
const subbed = await tool('update_task', { id: sub.id, project: 'Click Plumbing Co', parent: cap.id, add_tags: ['Phone'] });
assert(subbed.parent_id === cap.id && subbed.project === 'Click Plumbing Co' && !subbed.in_inbox && subbed.tags.join() === 'Phone', 'update_task: subtask + add_tags');
const groupView = await tool('get_task', { id: cap.id });
assert(groupView.sub_actions && groupView.sub_actions[0].id === sub.id, 'get_task lists sub-actions of a group');
const pruned = await tool('update_task', { id: sub.id, remove_tags: ['phone'], project: null });
assert(pruned.tags.length === 0 && !pruned.parent_id && pruned.in_inbox, 'update_task: removing project+tags returns item to Inbox (and detaches parent)');
const dropped = await tool('update_task', { id: sub.id, status: 'dropped' });
assert(dropped.status === 'dropped', 'update_task: drop');
const reopened = await tool('update_task', { id: sub.id, status: 'open' });
assert(reopened.status === 'open', 'update_task: reopen');
const done = await tool('complete_task', { id: cap.id, note: 'Spoke to Jan; bill moves next cycle' });
assert(done.completed_at && done.completion_note === 'Spoke to Jan; bill moves next cycle', 'complete_task records time + note');
const again2 = await tool('complete_task', { id: cap.id, note: 'Updated note' });
assert(again2.completed_at === done.completed_at, 'editing the note keeps the original completion time');
const review = await tool('list_completed', {});
assert(review.count >= 1 && review.by_project['Click Plumbing Co'] === 1 && review.items[0].completion_note === 'Updated note' && Object.values(review.by_day)[0] === 1, 'list_completed: this week, by project and day, with note');
assert((await tool('list_completed', { since: '2020-01-01', until: '2020-01-31' })).count === 0, 'list_completed respects date range');
assert((await tool('list_completed', { project: 'none' })).count === 0, 'list_completed filters by project');
const bad = await call('tools/call', { name: 'get_task', arguments: { id: 'nope' } });
assert(bad.body.result.isError, 'invalid id -> tool error, not crash');
const utcDue = db.tasks[0].due_at;
assert(utcDue === '2026-09-25T22:00:00.000Z', `due 5pm Chicago stored as ${utcDue}`);

// ---------- email capture ----------
assert(isAuthenticated('mx.cloudflare.net; dkim=pass header.d=douglasmining.com header.s=google; spf=pass smtp.mailfrom=robert@douglasmining.com; dmarc=pass', 'douglasmining.com'), 'auth: dmarc pass');
assert(isAuthenticated('dkim=pass header.d=douglasmining.com; dmarc=none', 'douglasmining.com'), 'auth: aligned dkim');
assert(isAuthenticated('dkim=fail; spf=pass smtp.mailfrom=bounce@mail.douglasmining.com', 'douglasmining.com'), 'auth: aligned spf subdomain');
assert(!isAuthenticated('dkim=pass header.d=evil.com; spf=pass smtp.mailfrom=x@evil.com; dmarc=fail', 'douglasmining.com'), 'auth: unaligned pass rejected');
assert(!isAuthenticated('', 'douglasmining.com'), 'auth: missing results rejected');
const t1 = emailToTask({ subject: 'Fwd: RE: Plans for Jodi', text: 'Please release all three.\r\n\r\n\r\n\r\nThanks', date: '2026-09-22T12:00:00Z', attachments: [{ filename: 'plans.pdf' }] }, 'robert@douglasmining.com');
assert(t1.title === 'Plans for Jodi' && t1.notes.includes('Attachments (not saved): plans.pdf') && !t1.notes.includes('\n\n\n'), 'emailToTask cleans subject, notes, attachments');
assert(emailToTask({ subject: '', html: '<p>Call GVEC</p><p>re: utilities</p>' }, 'a@b.c').title === 'Call GVEC', 'emailToTask falls back to first body line (html)');

const raw = (from, subject, body) => [`From: Robert <${from}>`, 'To: inbox@todotooling.com', `Subject: ${subject}`, 'Date: Tue, 22 Sep 2026 17:00:00 -0500', 'Content-Type: text/plain; charset=utf-8', '', body].join('\r\n');
const mail = (from, subject, body, auth) => { const m = { from, raw: raw(from, subject, body), headers: new Headers(auth ? { 'arc-authentication-results': auth } : {}), rejected: null, setReject(r) { this.rejected = r; } }; return m; };
const before = db.tasks.length;
const good = mail('robert@douglasmining.com', 'Fwd: Call 1st mortgage', 'Ask where to mail payment', 'i=1; mx.cloudflare.net; dkim=pass header.d=douglasmining.com; dmarc=pass');
await worker.email(good, env);
const made = db.tasks[db.tasks.length - 1];
assert(!good.rejected && db.tasks.length === before + 1 && made.title === 'Call 1st mortgage' && made.source === 'email' && made.user_id === UID && made.in_inbox, 'email from approved sender becomes inbox task');
const stranger = mail('someone@else.com', 'Buy crypto', 'spam', 'dmarc=pass');
await worker.email(stranger, env);
assert(stranger.rejected && db.tasks.length === before + 1, 'unknown sender rejected, no task');
const spoof = mail('robert@douglasmining.com', 'Spoofed', 'x', 'dkim=pass header.d=evil.com; dmarc=fail');
await worker.email(spoof, env);
assert(spoof.rejected && db.tasks.length === before + 1, 'spoofed From rejected, no task');
console.log('ALL PASSED');
